from setuptools import setup, find_packages

setup(
    name='django-cuser',
    version=".".join(map(str, __import__("cuser").__version__)),
    description='Middleware to make user information always available.',
    long_description=open('README.rst').read(),
    author='Alireza Savand',
    author_email='alireza.savand@gmail.com',
    url='https://github.com/Alir3z4/django-cuser',
    packages=find_packages(exclude=["django_cuser"]),
    install_requires=['Django>=1.5'],
    classifiers=[
        "Classifier: Development Status :: 5 - Production/Stable",
        "Classifier: Development Status :: 6 - Mature",
        "Classifier: Environment :: Web Environment",
        "Classifier: Framework :: Django",
        "Classifier: Intended Audience :: Developers",
        "Classifier: License :: OSI Approved :: BSD License",
        "Classifier: Operating System :: OS Independent",
        "Classifier: Programming Language :: Python",
        "Classifier: Programming Language :: Python :: 2",
        "Classifier: Programming Language :: Python :: 2.7",
        "Classifier: Programming Language :: Python :: 3",
        "Classifier: Programming Language :: Python :: 3.0",
        "Classifier: Programming Language :: Python :: 3.1",
        "Classifier: Programming Language :: Python :: 3.2",
        "Classifier: Programming Language :: Python :: 3.3",
        "Classifier: Programming Language :: Python :: 3.4",
        "Classifier: Topic :: Software Development",
        "Classifier: Topic :: Software Development :: Libraries",
    ],
)
